theme: minima
title: "Lonely traveler" 
author: "GitHub HY-F-6"
email: "HY-F-6@domain.com"
description: "www.traveler.hyf"

# social links
twitter_username: Hy-f-6 # DO NOT include the @ character, or else the build will fail!
github_username:  HY-F-6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
